[package]
name = "wifi-visualizer"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.4.12"
clap = "2.33.0"
env_logger = "0.7.1"
failure = "0.1.6"
futures-preview = { version = "0.3.0-alpha.19", features = ["async-await"] }
ieee80211 = { git = "https://github.com/SpiralP/rust-ieee80211.git", features = ["serde"] }
log = "0.4.8"
open = "1.3.2"
parceljs = { git = "https://github.com/SpiralP/rust-parceljs.git", features = ["warp"] }
pcap = { git = "https://github.com/SpiralP/rust-pcap.git" }
radiotap = "1.3.0"
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
tokio = "0.2.0-alpha.6"
warp = { git = "https://github.com/seanmonstar/warp.git" }

[target.'cfg(target_os = "linux")'.dependencies]
caps = "0.3.3"
