[package]
name = "wifi-visualizer"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.2"
clap = "2.33.0"
crossbeam-channel = "0.3.9"
env_logger = "0.6.2"
failure = "0.1.5"
ieee80211 = { git = "https://github.com/SpiralP/rust-ieee80211.git", features = ["serde"] }
log = "0.4.8"
open = "1.3.2"
parceljs = { git = "https://github.com/SpiralP/rust-parceljs.git" }
parking_lot = "0.9.0"
pcap = { git = "https://github.com/SpiralP/rust-pcap.git" }
radiotap = "1.3.0"
serde = "1.0.99"
serde_derive = "1.0.99"
serde_json = "1.0.40"
time = "0.1.42"
tiny_http = "0.6.2"
ws = "0.9.0"
helpers = { path = "../rust-helpers" }

[target.'cfg(target_os = "linux")'.dependencies]
caps = "0.3.3"
