[package]
name = "wifi-visualizer"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
boxfnonce = "0.1.1"
byteorder = "1.3.2"
error-chain = "0.12.1"
ieee80211 = { path = "../rust-ieee80211", features = ["serde"] }
pcap = { git = "https://github.com/SpiralP/rust-pcap.git" }
radiotap = "1.3.0"
serde = "1.0.97"
serde_derive = "1.0.97"
serde_json = "1.0.40"
time = "0.1.42"
ws = "0.8.1"
crossbeam-channel = "0.3.9"
parking_lot = "0.9.0"
parceljs = { path = "../rust-parceljs" }
tiny_http = "0.6.2"
open = "1.3.2"

[target.'cfg(not(windows))'.dependencies]
caps = "0.3.3"
