[package]
name = "wifi-visualizer"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
boxfnonce = "0.1.0"
byteorder = "1.2.7"
error-chain = "0.12.0"
pcap = { git = "https://github.com/SpiralP/rust-pcap.git" }
radiotap = "1.3.0"
serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0.36"
time = "0.1.42"
ws = "0.7.9"

[dev-dependencies]
criterion = "0.2.7"

[[bench]]
name = "bench_main"
harness = false
