[package]
name = "wifi-visualizer"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
pcap = { git = "https://github.com/ENOFLAG/pcap.git", rev = "ee44b9626dc4b392ab5e4750c8b49d539416a851" }
packet = "0.1.2"
error-chain = "0.12.0"
