[package]
name = "wifi-visualizer"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.2"
ieee80211 = { path = "../rust-ieee80211", features = ["serde"] }
pcap = { path = "../rust-pcap" }
radiotap = "1.3.0"
serde = "1.0.97"
serde_derive = "1.0.97"
serde_json = "1.0.40"
time = "0.1.42"
ws = "0.8.1"
crossbeam-channel = "0.3.9"
parking_lot = "0.9.0"
parceljs = { path = "../rust-parceljs" }
tiny_http = "0.6.2"
open = "1.3.2"
clap = "2.33.0"
log = "0.4.8"
env_logger = "0.6.2"
failure = "0.1.5"

[target.'cfg(target_os = "linux")'.dependencies]
caps = "0.3.3"
