[package]
name = "wifi-visualizer"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
error-chain = "0.12.0"
pcap = { path = "../rust-pcap" }
serde = "1.0.82"
serde_derive = "1.0.82"
serde_json = "1.0.33"
ws = "0.7.9"
boxfnonce = "0.1.0"
radiotap = "1.3.0"
byteorder = "1.2.7"
