[package]
name = "wifi-visualizer"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
boxfnonce = "0.1.1"
byteorder = "1.3.1"
error-chain = "0.12.0"
ieee80211 = { path = "../rust-ieee80211", features = ["serde"] }
pcap = { git = "https://github.com/SpiralP/rust-pcap.git" }
radiotap = "1.3.0"
serde = "1.0.87"
serde_derive = "1.0.87"
serde_json = "1.0.38"
time = "0.1.42"
ws = "0.7.9"
