name: Rust

on: [push]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: sudo apt-get -y update && sudo apt-get -y install libpcap-dev llvm clang

      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --nocapture

  build_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: |
          iwr -useb get.scoop.sh -outfile install-scoop.ps1
          .\install-scoop.ps1 -RunAsAdmin
          rm install-scoop.ps1
          echo "$HOME\scoop\shims" >> $env:GITHUB_PATH
          echo "C:\ProgramData\scoop\shims" >> $env:GITHUB_PATH
          scoop install aria2
          scoop install llvm
          echo "LIBCLANG_PATH=$HOME\scoop\apps\llvm\current\bin" >> $env:GITHUB_ENV
          Invoke-WebRequest -Uri 'https://nmap.org/npcap/dist/npcap-0.9987.exe' -OutFile npcap-0.9987.exe
          7z x -y 'npcap-0.9987.exe' '$SYSDIR\wpcap.dll' '$SYSDIR\Packet.dll'
          echo '.\$SYSDIR' >> $env:GITHUB_PATH

      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --nocapture

  build_mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: |
          brew install libpcap llvm
          echo "/usr/local/opt/llvm/bin" >> $GITHUB_PATH

      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --nocapture
